### PR TITLE
Removing logs in `logs/simona`.

### LINKED ISSUE #1017: Logs in two locations
There logs in `logs/simona` and in `output`. The former ones seem to be rather incomplete. This is very confusing and unnecessary.

Tasks:
- Get an understanding of what is happening here
- Probably we want to eliminate log output to the `logs` directory, as in the `output` directory, logs are placed next to their result files

### PR DESCRIPTION
**Pull request by staudtMarius**
Resolves #1017 

Merge first:
- #1032

### CODE REVIEW

**Comment by sebastian-peter** [comment]
Working on this and it avalanches into a bigger thing...

**Comment by sebastian-peter** [comment]
I'm done with my suggested changes, maybe both of you, @danielfeismann and @staudtMarius, want to have a look? The log level of the log file in the output directory can now be configured as well

**Comment by staudtMarius** [comment]
Looks good to me.

**Review by danielfeismann — APPROVED** [review]
LGTM

**Pull request merged**
