### PR TITLE
Remove gradle task for uml diagram export puml2png

### PR DESCRIPTION
**Pull request by danielfeismann**
resolves https://github.com/ie3-institute/simona/issues/228
resolves https://github.com/ie3-institute/simona/issues/156

### CODE REVIEW

**Review by sebastian-peter — APPROVED** [review]
LGTM

**Review by sebastian-peter — DISMISSED** [review]
Just realized an addition to the CHANGELOG is missing, could you provide it?

**Review by sensarmad — APPROVED** [review]
LGTM

**Review by sebastian-peter — APPROVED** [review]

**Comment by danielfeismann** [comment]
!test

**Review by sensarmad — APPROVED** [review]

**Pull request merged**
