### PR TITLE
Update gradle

### LINKED ISSUE #176: Update gradle
[New version available](https://gradle.org/releases/)

### PR DESCRIPTION
**Pull request by danielfeismann**
resolves #176

### CODE REVIEW

**Comment by danielfeismann** [comment]
>Executing 'help --warning-mode=all'...
Configure project :
The testRuntimeClasspath configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 8.0. Please use the testImplementation or testCompileOnly or testRuntimeOnly configuration instead. Consult the upgrading guide for further information: https://docs.gradle.org/7.3.3/userguide/upgrading_version_5.html#dependencies_should_no_longer_be_declared_using_the_compile_and_runtime_configurations
	at build_amq6f0xo666sjgmiy0jl7rcss$_run_closure4.doCall(...\simona\build.gradle:108)
	(Run with --stacktrace to get the full stack trace of this deprecation warning.)

@sebastian-peter let's have a short talk about this whenever it suites to you. Thanks :)

**Comment by sebastian-peter** [comment]
@danielfeismann this becomes relevant once gradle 8 is released (they're apparently going to deprecate some stuff), but of course nothing speaks against tackling these now

**Comment by sebastian-peter** [comment]
Ok well the `testRuntimeClasspath` can be replaced by `testRuntimeOnly` in this case (flexmark).
Would also be great to also add a comment `// scalatest html output` at the end of the line so that it's obvious why we need flexmark at all.
Also would be great if you could reverse your changes to `gradlew`

**Review by sebastian-peter — APPROVED** [review]
Looks good, thanks for considering my comments!

**Review by t-ober — APPROVED** [review]

**Pull request merged**
