### PR TITLE
Updated Gradle to latest Version v.8.10

### LINKED ISSUE #829: Update gradle to at least 8.8
Find out what's the newest version [here](https://gradle.org/releases/)

Also update gradle wrapper files, if applicable
Hint: `gradlew wrapper --gradle-version 8.8`

### PR DESCRIPTION
**Pull request by PhilippSchmelter**
Issue #829 asked to update to at least v8.8
Updated to v.8.10

Resolves #829 

Merge #909 First!

### CODE REVIEW

**Comment by PhilippSchmelter** [comment]
Somehow i failed while creating a new branch.. the changes i made for Issue #681 were copied into this branch. I hope it won't make merging all the stuff too complicated. If it's a big problem just tell me to start over.

**Comment by sebastian-peter** [comment]
@PhilippSchmelter I can show you at a later point how to handle these situations. It's no a problem here either because the other PR is already merged. Now you have to just merge back dev into your branch. Let me know if I can help you with that.

**Comment by PhilippSchmelter** [comment]
@sebastian-peter so the only thing left to do, is to merge the newest version of dev into my branch and then it's done? I think I've already done that once. I will message you if i face some troubles :)

**Review by sebastian-peter — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
