### PR TITLE
Write ThermalHouse results when em controlled

### LINKED ISSUE #844: Write ThermalHouse results when em controlled
At the moment thermal house results are not written out when the heat pump of the house is em controlled

Furthermore the fill_level of cylindrical thermal storages is not calculated correct

### PR DESCRIPTION
**Pull request by danielfeismann**
merge #842 first

resolves #844

### CODE REVIEW

**Comment by staudtMarius** [comment]
@danielfeismann There is a test failing in `StorageAgentModelCalculationSpec`.

**Comment by danielfeismann** [comment]
> @danielfeismann There is a test failing in `StorageAgentModelCalculationSpec`.

Yes, thanks. This arised after merging the new storage pr into dev. Working on it.

**Review by jo-bao — APPROVED** [review]
For me it looks good!

**Review by jo-bao — APPROVED** [review]
Nice!

**Pull request merged**
