### PR TITLE
Change transformer calculation

### LINKED ISSUE #99: Change transformer calculation
As of PowerSystemDataModel > 3.0 the no load susceptance of transformers (both two and three winding) will come negative. The automatic negation here should be adapted.

### PR DESCRIPTION
**Pull request by danielfeismann**
removed multiplier (-1) to comply with changes in PowerSystemDataModel >3.0

resolves #99

### CODE REVIEW

**Comment by danielfeismann** [comment]
To reviewers: Unsure if changes in ThreeWindingTestData are necessary (Test says not, but logically it needs to be changed there as well)

**Review by johanneshiry — DISMISSED** [review]
The changes LGTM, thanks for your work. 
However, did you also take into account the test input data (e.g. the vn_simona grid csv files). I'm wondering why the tests doesn't break here, because I would assume that at least the integration test _should_ fail? 🤔 
If this is not the case I'll approve it asap :) 

Regarding your question for 3 winding transformers maybe @ckittl can shed some light on this.

**Comment by danielfeismann** [comment]
> The changes LGTM, thanks for your work. However, did you also take into account the test input data (e.g. the vn_simona grid csv files). I'm wondering why the tests doesn't break here, because I would assume that at least the integration test _should_ fail? 🤔 If this is not the case I'll approve it asap :)
> 
> Regarding your question for 3 winding transformers maybe @ckittl can shed some light on this.

Thanks for your review. Also for remember me about the test input data. I checked them, they include just the reactance X not the susceptance B so this change doesn't effect the test input data.

**Comment by danielfeismann** [comment]
> To reviewers: Unsure if changes in ThreeWindingTestData are necessary (Test says not, but logically it needs to be changed there as well)

ThreeWindingTestData => #163

**Review by sebastian-peter — CHANGES_REQUESTED** [review]
There are still some files that in my eye need adaptation:

input/samples/vn_simona/fullGrid/transformer_2_w_type_input.csv
input/samples/vn_146_lv_small/fullGrid/transformer_2_w_type_input.csv

**Review by ckittl — APPROVED** [review]
Thanks a lot for your changes!

To all of us: Please be aware, that after this change, currently available grid models have to be revised thoroughly before using! This especially applies to the SimBench grids, as there the changes are not yet considered: ie3-institute/simBench2psdm#81

**Review by t-ober — APPROVED** [review]

**Pull request merged**
